# Generated by Django 4.2.7 on 2023-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.IntegerField(db_column='Id_Artista', primary_key=True, serialize=False)),
                ('nom_artista', models.CharField(blank=True, db_column='nom_Artista', max_length=50, null=True)),
                ('anno_nac', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id_cancion', models.IntegerField(db_column='Id_Cancion', primary_key=True, serialize=False)),
                ('album', models.CharField(blank=True, db_column='Album', max_length=50, null=True)),
                ('cancion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('vendidas', models.IntegerField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=52)),
                ('continent', models.CharField(db_column='Continent', max_length=13)),
                ('region', models.CharField(db_column='Region', max_length=26)),
                ('surfacearea', models.FloatField(db_column='SurfaceArea')),
                ('indepyear', models.SmallIntegerField(blank=True, db_column='IndepYear', null=True)),
                ('population', models.IntegerField(db_column='Population')),
                ('lifeexpectancy', models.FloatField(blank=True, db_column='LifeExpectancy', null=True)),
                ('gnp', models.FloatField(blank=True, db_column='GNP', null=True)),
                ('gnpold', models.FloatField(blank=True, db_column='GNPOld', null=True)),
                ('localname', models.CharField(db_column='LocalName', max_length=45)),
                ('governmentform', models.CharField(db_column='GovernmentForm', max_length=45)),
                ('headofstate', models.CharField(blank=True, db_column='HeadOfState', max_length=60, null=True)),
                ('capital', models.IntegerField(blank=True, db_column='Capital', null=True)),
                ('code2', models.CharField(db_column='Code2', max_length=2)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id_estilo', models.IntegerField(db_column='Id_Estilo', primary_key=True, serialize=False)),
                ('nom_estilo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estilo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(db_column='Id_Genero', primary_key=True, serialize=False)),
                ('nom_genero', models.CharField(blank=True, db_column='nom_Genero', max_length=50, null=True)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacion', models.IntegerField(db_column='Id_nacion', primary_key=True, serialize=False)),
                ('nom_nacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': False,
            },
        ),
    ]
