# Generated by Django 4.2.7 on 2023-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_4_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
