# Generated by Django 4.2.7 on 2023-11-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_4_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table='empleados',
        ),
    ]
