# Generated by Django 4.2.7 on 2023-12-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.IntegerField(max_length=10)),
                ('fecha_inscripcion', models.DateField()),
                ('hora_inscripcion', models.TimeField()),
                ('institucion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Participantes',
            },
        ),
    ]
