# Generated by Django 4.2.7 on 2023-11-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdCiudad', models.IntegerField(unique=True)),
                ('Nombre', models.TextField(max_length=50)),
            ],
        ),
    ]
