# Generated by Django 4.2.7 on 2023-11-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdRegion', models.IntegerField(unique=True)),
                ('Nombre', models.TextField(max_length=50)),
            ],
        ),
    ]
