# Generated by Django 4.2.7 on 2023-11-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdColegio', models.IntegerField(unique=True)),
                ('NombColegio', models.CharField(max_length=50)),
                ('Direccion', models.TextField(blank=True, null=True)),
                ('IdCiudad', models.ForeignKey(db_column='IdCiudad', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdComuna', models.IntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdEstado', models.IntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdLibro', models.IntegerField(unique=True)),
                ('Nombre', models.TextField()),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Autor', models.TextField(blank=True, null=True)),
                ('FechaPublicacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdRol', models.IntegerField(unique=True)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdTipo', models.IntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdUbicacion', models.IntegerField(unique=True)),
                ('Estanteria', models.CharField(max_length=50)),
                ('Nivel', models.CharField(max_length=50)),
                ('Segmento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarioestado',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdEstado', models.IntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('Nombres', models.TextField()),
                ('ApePat', models.TextField()),
                ('ApeMat', models.TextField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Telefono', models.IntegerField(blank=True, null=True)),
                ('IdColegio', models.ForeignKey(db_column='IdColegio', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.colegio')),
                ('IdEstado', models.ForeignKey(db_column='IdEstado', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.usuarioestado')),
                ('IdRol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('IdColegio', models.ForeignKey(db_column='IdColegio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks_colegio', to='biblio.colegio')),
                ('IdLibro', models.ForeignKey(db_column='IdLibro', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks_libro', to='biblio.libro')),
                ('Nombre', models.ForeignKey(db_column='Nombre', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks_nombre', to='biblio.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NroReserva', models.IntegerField(unique=True)),
                ('FechaPrestamo', models.DateTimeField()),
                ('FechaDevolucion', models.DateTimeField()),
                ('IdColegio', models.ForeignKey(db_column='IdColegio', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.colegio')),
                ('IdEstado', models.ForeignKey(db_column='IdEstado', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.estado')),
                ('IdLibro', models.ForeignKey(db_column='IdLibro', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.libro')),
                ('Rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='IdUbicacion',
            field=models.ForeignKey(db_column='IdUbicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.ubicacion'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='IdComuna',
            field=models.ForeignKey(db_column='IdComuna', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.comuna'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='IdRegion',
            field=models.ForeignKey(db_column='IdRegion', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.region'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='IdTipo',
            field=models.ForeignKey(db_column='IdTipo', on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.tipo'),
        ),
    ]
