# Generated by Django 4.2.7 on 2023-12-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
