# Generated by Django 4.2.7 on 2023-11-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_6_app', '0002_rename_fechainicido_proyecto_fechainicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechaInicio',
            new_name='FechaInicio',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechaTermino',
            new_name='FechaTermino',
        ),
    ]
