# Generated by Django 4.2.7 on 2023-11-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_6_app', '0003_rename_fechainicio_proyecto_fechainicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='FechaInicio',
            new_name='fechaInicio',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='FechaTermino',
            new_name='fechaTermino',
        ),
    ]
